# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f17558bc1c7ac5c0f7798b46a6b8e54238ec960954e4ae5f967bf1a9c988ce1c2ad12914ce7d81b7b960c101e0b74413ef7af01d57e8eb5fda6ec9e3aad1b9d5

test:
  secret_key_base: 04f6b7ac0c630ca9de4b5e58f4687b198a8edcf7c00ca955a8664839f93776b4a587879f902b15cab28b4057b9163ba1605c49f98fa70292145814dd2a94ae5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
